---
aws-account-id: "585031190124"
aws-ecr-region: us-east-1
project-name: force
post-deploy: 'mkdir -p /dev/udp/datadog/; echo "_e{18,18}:Force was deployed|force was deployed|#service:force" > /dev/udp/datadog/8125'